#!/usr/bin/env node
// SEOSONA Flow — Provider capability matrix (Phase 6 / P6.T8, AUD-018).
//
// Crosses every provider profile against every contract capability and assigns
// each cell a VERIFIER DISPOSITION so no capability is left unaccounted for:
//   - pass        : verified offline (a clean fixture exercises it, or a unit
//                   contract proves it)
//   - unsupported : the provider explicitly declines the capability
//   - deferred    : only meaningfully verifiable in a controlled live browser
//                   (upload, live cancel) — covered by the Playwright smoke, not
//                   by an offline fixture
//   - fail        : implemented + offline-verifiable but NO fixture exists
//
// It also asserts the whole fixture corpus is free of authenticated traces
// (privacy: clean). Writes a deterministic JSON + Markdown artifact; `--check`
// reconciles them so drift breaks CI.
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { repoRoot, stableJson } from '../audit/lib/repo.mjs';
import { loadClassic } from '../../tests/helpers/load-classic.mjs';
import { scanForPrivateData } from './sanitize-provider-fixture.mjs';

const ROOT = repoRoot();
const FIX = join(ROOT, 'seosona-flow/tests/fixtures/providers');
const JSON_OUT = join(ROOT, 'seosona-flow/artifacts/providers/phase-06/provider-matrix.json');
const MD_OUT = join(ROOT, 'docs/testing/provider-matrix.md');

const PA = loadClassic('src/providers/ProviderAdapter.js').SEOSONA_ProviderAdapter;

// How each capability is verified, and which fixture state(s) exercise it.
const VERIFY = {
  readiness:    { via: 'fixture', states: ['ready'] },
  login:        { via: 'fixture', states: ['logged-out', 'ready'] },
  prompt:       { via: 'fixture', states: ['ready'] },
  status:       { via: 'fixture', states: ['generating', 'complete'] },
  results:      { via: 'fixture', states: ['complete'] },
  challenge:    { via: 'fixture', states: ['challenge'] },
  errors:       { via: 'unit' },     // ProviderError.normalize — offline contract
  abort:        { via: 'unit' },     // PageBridge / cancellation — offline contract
  attachments:  { via: 'browser' },  // file upload — controlled smoke only
  cancellation: { via: 'browser' },  // live stop button — controlled smoke only
};

function fixtureStates(provider) {
  const dir = join(FIX, provider);
  let names;
  try { names = readdirSync(dir); } catch { return new Set(); }
  return new Set(names.filter((n) => n.endsWith('.html')).map((n) => n.replace(/\.html$/, '')));
}

function corpusFindings() {
  const problems = [];
  (function walk(d) {
    for (const n of readdirSync(d).sort()) {
      const p = join(d, n);
      if (statSync(p).isDirectory()) walk(p);
      else if (n.endsWith('.html') && scanForPrivateData(readFileSync(p, 'utf8')).length) problems.push(p);
    }
  })(FIX);
  return problems;
}

function build() {
  const caps = Object.keys(PA.CAPABILITIES);
  const rows = PA.providers().map((provider) => {
    const profile = PA.PROVIDER_PROFILES[provider];
    const states = fixtureStates(provider);
    const cells = {};
    for (const cap of caps) {
      const supported = profile.supports[cap] === true;
      if (!supported) { cells[cap] = 'unsupported'; continue; }
      const v = VERIFY[cap];
      if (v.via === 'unit') { cells[cap] = 'pass'; continue; }
      if (v.via === 'browser') { cells[cap] = 'deferred'; continue; }
      // fixture-verified: pass if any exercising state has a fixture
      cells[cap] = v.states.some((s) => states.has(s)) ? 'pass' : 'fail';
    }
    return { provider, version: profile.version, cells };
  });

  const tally = { pass: 0, unsupported: 0, deferred: 0, fail: 0 };
  for (const r of rows) for (const cap of caps) tally[r.cells[cap]]++;

  const privacyClean = corpusFindings().length === 0;
  return {
    schema: 'seosona.providers.matrix.v1',
    contractVersion: PA.CONTRACT_VERSION,
    capabilities: caps,
    privacy: privacyClean ? 'clean' : 'leak',
    tally,
    rows,
  };
}

function toMarkdown(m) {
  const caps = m.capabilities;
  const head = ['| Provider | ' + caps.join(' | ') + ' |'];
  head.push('|' + '---|'.repeat(caps.length + 1));
  const body = m.rows.map((r) => '| ' + r.provider + ' | ' + caps.map((c) => r.cells[c]).join(' | ') + ' |');
  return [
    '# Provider Capability Matrix',
    '',
    '> Generated by `scripts/test/provider-matrix.mjs`. Do not edit by hand — run the script.',
    '',
    `- Contract version: **${m.contractVersion}**`,
    `- Fixture privacy: **${m.privacy}**`,
    `- Dispositions: pass=${m.tally.pass}, unsupported=${m.tally.unsupported}, deferred=${m.tally.deferred}, fail=${m.tally.fail}`,
    '',
    '**Legend:** `pass` = verified offline (fixture/unit) · `unsupported` = provider declines · `deferred` = controlled browser smoke (Playwright) · `fail` = missing coverage.',
    '',
    ...head,
    ...body,
    '',
  ].join('\n');
}

function main() {
  const check = process.argv.includes('--check');
  const m = build();
  const json = stableJson(m);
  const md = toMarkdown(m);

  if (check) {
    let curJson = null, curMd = null;
    try { curJson = readFileSync(JSON_OUT, 'utf8'); } catch { /* missing */ }
    try { curMd = readFileSync(MD_OUT, 'utf8'); } catch { /* missing */ }
    const problems = [];
    if (m.privacy !== 'clean') problems.push('fixture privacy leak');
    if (m.tally.fail > 0) problems.push(`${m.tally.fail} capability cell(s) have no coverage`);
    if (curJson !== json) problems.push('matrix JSON drift');
    if (curMd !== md) problems.push('matrix Markdown drift');
    if (problems.length) {
      console.error('[matrix] check failed: ' + problems.join('; '));
      console.error('  regenerate: node scripts/test/provider-matrix.mjs');
      process.exit(1);
    }
    console.log(`[matrix] OK — ${m.rows.length} providers, ${m.capabilities.length} capabilities, privacy ${m.privacy}, 0 fail.`);
    return;
  }

  writeFileSync(JSON_OUT, json);
  writeFileSync(MD_OUT, md);
  console.log(`[matrix] wrote matrix (${m.rows.length} providers × ${m.capabilities.length} capabilities).`);
}

import { fileURLToPath } from 'node:url';
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
export { build };
