#!/usr/bin/env node
// SEOSONA Flow — SBOM + third-party notices (Phase 9 / P9.T4, AUD-028).
// Emits a minimal CycloneDX 1.5 SBOM covering BOTH npm dev dependencies (from
// package-lock.json) and vendored in-repo libraries (from the security vendored
// baseline). Fails if any vendored library is not registered. Deterministic
// artifact + `--check`, plus a human-readable third-party notices doc.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { repoRoot, sha256, stableJson } from '../audit/lib/repo.mjs';

const ROOT = repoRoot();
const LOCK = join(ROOT, 'seosona-flow/package-lock.json');
const VENDORED = join(ROOT, 'seosona-flow/artifacts/security/vendored-baseline.json');
const OUT = join(ROOT, 'seosona-flow/artifacts/release/phase-09/sbom.json');
const NOTICES = join(ROOT, 'docs/legal/third-party-notices.md');

function npmComponents() {
  const lock = JSON.parse(readFileSync(LOCK, 'utf8'));
  const out = [];
  for (const [path, meta] of Object.entries(lock.packages || {})) {
    if (!path.startsWith('node_modules/')) continue;
    const name = path.replace(/.*node_modules\//, '');
    out.push({
      type: 'library', name, version: meta.version || '0.0.0',
      purl: `pkg:npm/${name}@${meta.version || '0.0.0'}`,
      licenses: meta.license ? [{ license: { id: String(meta.license) } }] : [],
      scope: 'optional', // dev-only tooling
    });
  }
  return out;
}

function vendoredComponents() {
  const v = JSON.parse(readFileSync(VENDORED, 'utf8'));
  const list = Array.isArray(v) ? v : (v.files || v.vendored || []);
  return list.map((e) => ({
    type: 'library', name: e.path, version: 'vendored',
    purl: `pkg:generic/${e.path}`,
    hashes: [{ alg: 'SHA-256', content: e.sha256 }],
    scope: 'required', // shipped in the extension
  }));
}

function build() {
  const npm = npmComponents();
  const vendored = vendoredComponents();
  const components = npm.concat(vendored).sort((a, b) => a.purl.localeCompare(b.purl));
  // A serial number derived from content (no timestamps — deterministic).
  const serial = 'urn:uuid:' + sha256(components.map((c) => c.purl).join('\n')).slice(0, 32).replace(/(.{8})(.{4})(.{4})(.{4})(.{12})/, '$1-$2-$3-$4-$5');
  return {
    bomFormat: 'CycloneDX',
    specVersion: '1.5',
    serialNumber: serial,
    version: 1,
    metadata: { component: { type: 'application', name: 'seosona-flow', version: JSON.parse(readFileSync(join(ROOT, 'seosona-flow/manifest.json'), 'utf8')).version } },
    componentCounts: { npm: npm.length, vendored: vendored.length },
    components,
  };
}

function notices(sbom) {
  const lines = ['# Third-Party Notices', '', 'Generated by `scripts/security/generate-sbom.mjs`. Do not edit by hand.', ''];
  lines.push('## Vendored (shipped) libraries', '');
  for (const c of sbom.components.filter((c) => c.scope === 'required')) lines.push(`- \`${c.name}\` — SHA-256 \`${(c.hashes && c.hashes[0] && c.hashes[0].content || '').slice(0, 16)}…\``);
  lines.push('', '## npm dependencies (dev tooling)', '');
  for (const c of sbom.components.filter((c) => c.scope === 'optional')) lines.push(`- \`${c.name}@${c.version}\`${c.licenses.length ? ' — ' + c.licenses[0].license.id : ''}`);
  lines.push('');
  return lines.join('\n');
}

function main() {
  const check = process.argv.includes('--check');
  const sbom = build();
  const json = stableJson(sbom);
  const md = notices(sbom);
  // Gate: every vendored library must be registered as a required component.
  if (sbom.componentCounts.vendored < 1) { console.error('[sbom] no vendored components registered'); process.exit(1); }
  if (check) {
    let curJson = null, curMd = null;
    try { curJson = readFileSync(OUT, 'utf8'); } catch { /* missing */ }
    try { curMd = readFileSync(NOTICES, 'utf8'); } catch { /* missing */ }
    if (curJson !== json) { console.error('[sbom] SBOM drift — run the generator.'); process.exit(1); }
    if (curMd !== md) { console.error('[sbom] notices drift — run the generator.'); process.exit(1); }
    console.log(`[sbom] OK — ${sbom.componentCounts.npm} npm + ${sbom.componentCounts.vendored} vendored components.`);
    return;
  }
  mkdirSync(dirname(OUT), { recursive: true });
  mkdirSync(dirname(NOTICES), { recursive: true });
  writeFileSync(OUT, json);
  writeFileSync(NOTICES, md);
  console.log(`[sbom] wrote SBOM (${sbom.components.length} components) + notices.`);
}

import { fileURLToPath } from 'node:url';
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
export { build };
