/**
 * VeoWatermarkProfile — alpha-map HIỆU CHỈNH cho watermark video Veo + phép TRỪ NGƯỢC chính xác.
 *
 * ══ ĐO TỪ ĐÂU ══
 * Đo trực tiếp trên video Veo thật 1080x1920 (240 khung, H.264) do người dùng cung cấp
 * (2026-07-27). Không phỏng đoán, không lấy từ repo khác — alpha-map của allenk/VeoWatermarkRemover
 * nằm trong file .exe C++ nên không dùng lại được cho JS.
 *
 * Cách đo: watermark ĐỨNG YÊN, nội dung ĐỘNG ⇒ với mỗi pixel, hồi quy qua 240 khung × 3 kênh
 *     in = (1-α)·bg + α·L
 * với bg = mặt phẳng khớp trên vành ĐỐI XỨNG quanh sao (khử dốc sáng nền). Kết quả:
 *     α lõi = 0.32   ·   màu logo L ≈ 233 (trắng, KHÔNG có nét viền đậm)   ·   R² = 0.94
 * Sai lệch so với nền xung quanh: 49.7 → 5.8 mức xám (giảm 8.6 lần).
 *
 * ══ HÌNH HỌC ĐO ĐƯỢC (1080x1920) ══
 *     tâm sao = (900, 1740)  ⇒  cách mép phải 180px, cách đáy 180px, tức 1/6 CẠNH NGẮN
 *     kích thước sao ≈ 91px ≈ 8.4% cạnh ngắn
 * LƯU Ý TRUNG THỰC: chỉ có MỘT video để đo, nên tỉ lệ suy rộng cho độ phân giải khác là SUY
 * ĐOÁN. Vì vậy VeoWatermarkProbe (tự dò theo thời gian) LUÔN được ưu tiên; bảng này chỉ dùng
 * khi dò thất bại (cảnh gần như tĩnh).
 *
 * Đối chiếu với code CŨ: boxFor() đặt ô 96px ở lề 64 ⇒ chỉ chồng ~5% lên watermark thật.
 */
(function (root) {
  'use strict';

  var MAP_W = 81, MAP_H = 75;
  var OFF_X = -37, OFF_Y = -37;   // góc trên-trái của map so với TÂM sao
  var PEAK = 0.3872;
  // Màu logo = TRẮNG TINH. Ước lượng đầu tiên của tôi cho 233 nhưng đó là do mô hình nền còn
  // thô; quét đối chứng trên video thật (L=233 vs L=255) cho L=255 sai lệch thấp hơn hẳn.
  var LOGO = 255;
  var REF_SHORT = 1080;              // cạnh ngắn của video đã hiệu chỉnh
  var CENTER_INSET = 180 / 1080;     // tâm sao cách mép = 1/6 cạnh ngắn (đo được)
  // Cỡ ngôi sao THẬT trên video 1080x1920 = 72px (map 96px ở tỉ lệ 0.75).
  //
  // ĐÍNH CHÍNH: lần đầu tôi chốt 67px do THƯỚC ĐO SAI — chỉ chấm điểm trên pixel NẰM TRONG vết
  // map, nên map càng nhỏ càng ít bị chấm ⇒ điểm tốt giả. (Bằng chứng: map 36px ở tỉ lệ 0.45,
  // tức chỉ 16px, cũng được điểm gần bằng map 67px dù không thể phủ nổi ngôi sao.)
  // Đo lại trên VÙNG CỐ ĐỊNH 90x90 bất kể cỡ map: 72px là đáy thật (5.599), 67px là 5.753.
  // Phủ thiếu 5px chính là cái viền còn sót ở bản trước.
  var STAR_RATIO = 72 / 1080;

  var B64 = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+3WhOzYu2zwW9YM9RfO9PVHStz1qmW09Oh+xPMFhUzsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJUG2zn/s786UqYWO+KpFjtayb86ij/bOQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsVtVPCZtbz2MTQI+7FU2PhA8Lz6oruU9FWg+PTYNFzwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABOrDg6wbDLPNFuwT0vOUA+U8yCPoluej4gSyc+/cyYPZ2DkTwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABT6mQ7faskPVqoAD5rimY+eMCWPuAUkD5zB0g+YBHOPXA79zyeDOI6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAo17TObOKuzrujhQ75jQVO4luvzozvt05AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABWCxs87vVxPTG6Gj4kbHk+cZCaPniQlD5JeV0+UEoDPmu8TD2B6fs7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwkN455R8nO5LI1jv4uiI8d1QlPOJU4jvBODk7FeEEOgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFNebDq1xKc8ZZGrPSAKNj76PIU+YSCbPlf4lj6jIXc+tusmPiiwoj0R/aU8v+yGOgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP3Q3DlnIL86mjMVO/65LzuiXIM7WjUKPDVjgzxHe7g8YVC9PPrVjTy32BU8w45KO3vHAjoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG5RpDuo8yA9ZjDtPQyOVD6x9Yw+WGKZPmFplz46sIg+xFdQPjUl8j2tqCo9UAOvOwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2L7YObZAxDoSfjg7kvxiOylQjTuYWto7DbIKPBlCFDym7iw8AXuDPDIK1zwJjhA9u9oUPWVr6TwkkYg87QbXO1p5ozoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANrfROamoZTx0z4U90o8aPh/RcT6DdpI+RamWPulolj4ZcZI+E3F1PgjdID5ysYs9uPhbPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACN29w5EVcnO4Yo2TsNEi48kSo+PKxtNDxGuUo8MoNhPCHeYzwymnA8nnSePAyQ7zw9+x09QMYiPcDiAT3Eyp48oSgCPDkrxDoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+OZjO/mb/jziTsk9HSw+PgVZhD5mb5Q+9N+TPuzClD4gEZc+M5CHPlc1Qj50TsY9uhbaPK3GyzoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4CYo6ZcSyO/9VVzy+F6E8I+WjPGUlhTxaPGk8pZVlPM4dYTytsF08BYuCPK/buTx/bfE8v5v4POXVyDzUjnw8fW7VO1p5ozoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoxs0PJm4aT1E4Qs+A3JgPvZAjD6AhJM+fqSRPhl3kz4YB5g+5ZiPPh8rXz5MKgM+nudAPaK15TsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACqpKU6x1LZOzUPgzxG7788VmK9PBWkijzfRjo8ZekWPCIBDDyzQf07xbAIPE7AQDyXZn48D0WCPO4zTTxH/Pk7q5FGO3vHAjoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACcbhs7fCPbPOYRuz1yxDQ+YUR+PnPpkD6XHJI+10eRPueXkz40XZc+Yd+TPtiXeD51CiY+v8icPVy9ozxratE6CBvyOeVQlzpGlLU65VCXOggb8jkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4CYo6MemyOxSBVTwF4Zc8EvOPPOTPPDymlq87MMc1O2q3GTs4rPo6L1kCO2mgQzt2P4k7cDSLO66uSjs+2No6qv78OQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIr5FDpeiDM8KXRfPZYNCT5jGl4+2laLPu+Ikz6DEZI+8OaSPkUplT5DFZc+tJKWPiyNiD5idk4+EW/wPUQ4OD1enhM8klliO8KYxzsJL+875L7BO7qgMjsa3OY5AAAAAAAAAAAAAAAAAAAAAAAAAACN29w5ELMnOzuU1Ds+CRc8ZU0MPLnhqDv+Q786AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFlJjDvivfg80obBPaQLOT6dlYE+LYmTPjH3lD7EeJM+XzqVPu7jlj50S5c+iSKYPty1kj5uF3g+jXMqPvGGqj0IZts8Gf8aPBYGPDyPNmE8wLU0PGsbrjuQSZA6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPeXZOQrtvDotoxM7SjQTO7tTujoT99I5AAAAAAAAAAAAAAAAMNjgOd6UwzpaIzQ77VpcO3/vMTs6E746wwjYOQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnhexOhoXhDzQ74Q91XEVPukXaj6/6o8+bBGXPiNVlT6bd5U+1ZaXPryWmD6pGpg+kqaYPsSRmD4FMY0+leddPqAmCD6r4W49a96nPKQ/YjziSXU8xwtEPKRIwDsTJa06AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACDo9Y5i64qO/Yp3DvO4jU8RBNQPLccIjwDaKw7oTHDOgAAAAAAAAAAaL7fOQHXizrOzqc6AdeLOmi+3zkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqwLkOzSvJj3ADec9GbNOPkyfij7hHpk+OV2YPqs9lj5ku5c+Ts6ZPr+Omj6FA5o+5M+ZPlZymz6ed5g+UDeFPp1IPz5VltA9KywlPTigejx+0TM8h+EOPArYjzuQSZA6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3XrgOQMHwToYink7sT4XPKKrijzIrsU857DVPHq7pjwy+To8pKF+O5p72DkAAAAAAdeLOsHMLjuBwlE7wcwuOwHXizoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABo/DI7OvvBPM7tpz25ay4+zPiBPsS7mT78FZ0+HdmYPq60lz5Eipk+/1GbPqgTnD6dv5s+0QqbPhcbnD4WM50+mVCUPr+zcD7qKxs+yTqSPYEutzx3K707qlhGO47wzToa3OY5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABLD3TnKwsc6R/SBO2skADy98FU8W4OtPB2V+zw5/R09gyciPfLc/Dyyc5I8EEDbO0BNhzoAAAAAzs6nOoHCUTs0tns7gcJRO87OpzoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEwGojoS5148i5ZpPRBWDD50nmk+2RKWPg/uoD6NTZ0+HMSYPjVumD5IF5o+NKObPt93nD6VSZw+bW6bPgaPmz4pX50+OFSbPsyjij7vn04+tr7uPRBnQD3ymTQ8uomNOgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAp30jlmioM6CIjSOqUfaDvbH+k7+LdPPNs+oDyZqdk81c0OPTL6MD0N9kg9wQVDPegtFT3mlqw8CEQBPLNcojoAAAAAAdeLOsHMLjuBwlE7wcwuOwHXizoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG/4IOpOgADxBLx49HMPYPTlQSD5C8Is+4+efPuD2oD7/iZs++WqYPng+mD58UZk+AYuaPnR1mz7Ee5s+q8KaPrB2mj5Klps+oUecPokjlT42yHs+RLAvPneivD036ws9M37sO4uOCzryQOQ5zE7KOgdmOjuuYYA7htqAO85+OjuxQsw6yNfyOWaKgzoAbSQ7BZWDOxgSAjw/eW08GWa+PO1WBD2qbiA91I44PchJTT2vq1Y9VTREPfnTED2pJKI85SnnO0BNhzoAAAAAaL7fOQHXizrOzqc6AdeLOmi+3zkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApKiVO+LL3zyz5Kg9DF8pPv6AfT6eXZk+E9KgPrh6nT5acJk+IK6XPitZlz4Jxpc+rquYPtalmT4k45k+xFqZPhYWmT4S45k+3RGbPtnTmT6TAI8+V7BoPrtFGz4Q+ps92KHNPDFRhjsDqMg647CiO40/CjxQvTk8ynJBPEslJDz52fY7ZmOIO5IxVjuAxZM7Kr7FO6SkNTygHKI8H6f7PJOaJj3jCzw9ZTpGPV32TD2uyUc9ZhApPdKL5jx3Bmo8+9eNO5p72DkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACaF0Y7kD2rPDGFij0q5BE+copkPuH1jz7gJpw+Py6cPpYPmT7dNJc+h4KWPhJilj7fq5Y+O3qXPq95mD6f3pg+p4+YPjSPmD79ppk+egCbPqF6nD76vZo+0f+MPm0XXj4Kagw+rCOCPSY2nzwB/sg7twoVPPDyazxIvJs8Z/yjPInOmTxGTIY8f14tPJ4q7DtKrto7XjHnO9PEPTwaKKA81yvzPDkBHj3CUyw9b8ktPVFTKz2FMhw9hRTxPAASkjwSgv07oZLpOgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOY7Mzui+JQ8kw51PZeYBD7yYlQ+hGWIPjxqlj7uIpg+OCeWPqYVlT5I95Q+u0+VPsPVlT5Nk5Y+IrmXPpL2mD4Lrpk+hsmZPs5Fmj7c7Zs+bsydPoM0oD5D06I+2gefPqwfjT5BbFU+U0MAPm4qaD3fj7Q82NuAPBSDpTwkTtI8bK/SPHPKwjybEq88yoFrPLzFFjyNbdY7bSqsOzG6ATzmMVg8G1qnPBrp3TwzqfE8qmPvPBGH4zyonsA89kuFPC/pCTymVTw76EwDOgAAAACuIfI5reXQOmnBIjt2AyI7+nHMOn1C5jkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzLwVO1XihjzbNmI9VZL5PWF/TD6JQIU+we+TPlCilT5e55I+YMaRPndVkj4FTJM+QGGUPh6GlT6v8pY+vc2YPuSrmj4nI5w+ISOdPvaBnj5V0KA+kSajPta1pT4zDak+G0OqPr/+oj6OeIw+AnpNPpgX8z12yG099MPxPGrGuzxZhss8pFC9PKRcpjwcx5c8VklVPN3VBzzf0qM7sjhHO5gVhDswHtM77TQnPMRuZTzP5Hs8o+h2PCabYTw6+C48FkHSO7HnIztd8Ns5AAAAAOUa6zk8zjg7/sLrO22bLzyKrDY8qJYGPMhehTv6VMc6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB70C07xxeFPFtpWD2Zle49cJhFPhP9gj6FDpM+DCqVPhGdkT6YM48+qHSPPiDdkD46gJI+UgyUPrejlT4RrZc+gkSaPvLenD7qJJ8+pyGhPqpwoz7FPqY+88qoPrlIqz4M/K0+1SiwPh0grz5gjqQ+ICCLPnWuST6r+fM9pAt8PffJ/Txmoac8VCt9PEF+QjwVICc8gC7sOxofmTsbnyY7jmCfOotIuzqDrvo6tlI6O14xgDtduYw7qpyJOwrScjtfmC47URm7Op0k0zkAAAAAAAAAADNezTomRuw7DNCCPAzXvDxEcMU8/iaXPEyDKDwWw4o7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEmhRDs2Oo08p2lXPZu75z3cDz8+O9Z+Pl32kD5pdpQ+P22RPv6fjj6wBo4+hhOPPsbrkD4E8pI+gL2UPgCRlj5l+pg+MQ2cPngonz6K5qE+sHKkPixEpz7KVao+bvmsPmIlrz4q+rA+hmiyPpgTsz5MA7A+IqmjPjlaiT5De0c+86P0PSgWez1jk+Q8yMdFPNYToTuyDCw7TmHcOmrHiDqq2No5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACqZ+s5ytHNOspXsDuiFmw8je/VPBMEDj3oDw49WqDTPFPHaTys8rg7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApxkfOyKXiDzxMlY9hxnjPV8COj5panc+4jSNPvwvkj7eWJA+iVqOPuYnjj7L4I4+X1iQPl5fkj7FeZQ+lliWPgBHmD7n2Jo+JA6ePiI2oT633KM+nkOmPg/rqD6x7as+3rWuPtCzsD7E2LE+7VmyPmaIsj4Z8LE+Z/qtPnapoD4mY4Y+hFVFPlyo9T1ajX490vbTPOgT7ztOH4A6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADKIJM6HqOAOxj1Hzycy6I8hKP6PB6sFz1rfQ899snNPM1VXTwJH6c7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFHePDqNJJk71K2XPFPqWD3sH+E92jI2Phe6cj5uhYo+haiPPojejj7UkY0+3B2OPleFjz5L/pA+lLaSPma1lD7SrpY+rYqYPhGHmj5hFJ0+4B6gPnnyoj4OC6U+fa2mPviBqD6R9ao+n7+tPv4DsD65G7E+dg2xPqeAsD7kra8+cZGuPlXVqT7Vkpw+QzSFPq1nST5REwM++YWNPaiB5zxFU/s71TOJOgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC/jbA6V12aO5c4KTxMjpQ89QPMPEG44jy2QMg8XQaGPPLeAzxekCo7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjgXjOmyDEjxuwds885d7PaAe7D3r8jY+kWhvPiTziD6qeo4+NmaOPh4Ijj7X1I4+O4eQPl5Ukj5kB5Q+J7WVPvJtlz4MEZk+Q7SaPvaHnD5/yZ4+62KhPlWwoz4BKqU+//ulPsLXpj6Be6g+XvOqPuJcrT4aq64+DaOuPjrprT4Dzaw+s82rPrkcqj7SiKU+EZibPv0GiD5Qe1Q+MSQPPgVxnj0Pwwk9/6MyPJaNBTsAAAAAAAAAAAAAAACr9Ag67bbhOtzdKjuMYCc7DcfMOlgU2jkAAAAAAAAAAAAAAADKIJM6HqOAO0r3/TuoXEM8sxZwPGd8bzzhQj48mP3eO1YcKDud3+I5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADqnBDoetYg7f72CPDmAIz1SAaA9CL8EPrmIPz5eF3I+G7yIPny6jj7QPY8+F4WPPp7MkD6EV5I+ixSUPqLNlT6TY5c+r8yYPpkOmj6WI5s+IUecPnCknT6oT58+AzuhPh7eoj5DwKM+qPmjPi8epD45AKU+5eimPqIeqT7OpKo+yS6rPvckqz7yxqo+3CiqPgARqT6ce6c+QQWlPhN3nT4XE4w+v05hPrb2Hj5UM8I97pJLPczGrDwO2N87m+u5OixLBjrxpFA7683/OxB2MDzYqyA8rj66Ox85xjoAAAAAAAAAAAAAAACqZ+s5ytHNOsF8PztygoY7CKSWOy/ehjtrsUA751bIOlCT1zkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxIY0OykEPjzeMfg8MGZ9PUnl0z2uHBw+Tw9QPrtxez5DQIs+MW+QPqMekT7ji5E+cESTPvz3lD5HMZY+hHSXPo7HmD63EJo+Qx2bPvPemz7gWpw+MuicPp6xnT5CsZ4+WOCfPrfWoD6uNqE+UhChPvPSoD4hNaE+lp6iPuqSpD6uVKY+6KynPinJqD4ntqk+tzmqPoz2qT6/BKk+ToSoPptApz7ePKE+bxCTPkQVdz6auzw+wc0BPmpSnT2z6CM9BxWKPME+2zuoTwA8Rip8PGzjqTwKdJc8lActPJlqOTsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL7o6TosowU8XDjNPHZWYD0R48A9EOQOPjcEPD5fLGU+802DPuTajT7Wa5I+hhOTPuhakz7Cy5Q+AguXPhawmD5SeJk+YQyaPlfCmj6tnZs+50icPk+cnD7olpw+CJ+cPozqnD5ybZ0+OReePriRnj7Hn54+lVeePmgUnj7hZ54+DrqfPhSnoT4zoaM+nKClPlvBpz5b/ak+9tmrPhzGrD4Loqw++kOsPsqBrD6VYaw+rtCoPhU1nj6XH4s+ln9iPtznKT4a8uc9P7GMPVHTHT3eX88870nVPIJu7DyGscY8t6ViPDZifTsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMtWHjpKP4E7/Us4PNdazDwlH0Y9z9itPbm3Bj7xXDc+wO5gPko2fj7GJIk+xV6PPsV2kj4tv5M+rzyUPt6YlT6AjJc+Mp+ZPnDomj4WNZs+BTubPvh4mz4PA5w+l3ycPrqenD4WVpw+Gg+cPqkRnD6rYZw+8+OcPjFEnT4mVZ0+6TOdPtM0nT7ay50+ZFSfPlFsoT7emqM+tPOlPpyYqD6mjas+KWeuPmJwsD6ESrE+qFexPgSFsT7jYrI+qbayPmVjsD7peqg+fFGZPg2ShD6og1Y+JCAhPusi5T0f/549meRpPTbNLz3aY+M8HUljPOtHejsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqYnc6ikKzOwuZgDxf4Qk9QJFuPfFPsz3efPw9UKwqPht5WT5fvH8+ySWLPrAfjz7JpZA+zwySPnt7kz5xz5Q+NM2VPoBxlz7cOpk+hLWaPkRumz5ZRZs+KOWaPgTemj6DSps+6NObPlEZnD6+7Js+d62bPoG1mz7PJJw+4+KcPsKYnT6iEZ4+VWCePmjOnj7Yup8+JHOhPlWXoz7fuKU+hfynPqSZqj7Wpa0+D9iwPqJ5sz4S9LQ+f5K1Pt/atT6ZG7Y+dvK1Pv8ktT7Tq7I+mGmtPnTApD5iyJU+e3OBPvbYVT6yDSg+YrL+PakSsz13NVc9t9DRPMyGCjxIwZM6AAAAAAAAAAAAAAAAAAAAANP18zmkeZg67ZDuOoW7ETsix+M6Zv2KOj1i3jkIlOc5AAAAAAAAAAAAAAAAiCOaOpIhujuBhoQ80F8VPYfwhj0pBs89MZUMPgVRLj6j9E8+/qpyPh82iD4nI5E+qR6TPn6dkT6tcpE+3hOTPi4OlT4+iJY+GGaXPqyYmD7pyJk+1IuaPjy5mj6+UJo+AtiZPrbHmT49QZo+0A+bPtDDmz6MApw+nxCcPpNfnD7SMp0+E3KePuCwnz72qqA+PXOhPndCoj6CV6M+DO+kPrS4pj4uWqg+6w2qPvMtrD5X4K4+YNWxPhpftD7P67U+xtK2PqFmtz75a7c+6nS2Pr+gtD52hLI+bTmxPoqPsD4RyKw+UR2kPv4plj4ISYM+JQ9cPuu8LD5z0fU9rc2bPTUOKj3X+aE80f0UPN/imDuG/U07anwPO6TWRjsBgpU74oS/O/yC2Tvkf5w7v7wtO0UCwDq71yg73fzNOhAS3zsuNng8ZwrbPBISMj06eIs9pvPTPccUFD5+KTw+R6ddPs/JdT6kHIQ+fIiLPrwekD6P6JE+/pORPqIxkT6lz5I+OlqVPgpWlz5Oe5g+696YPl1WmT7N4Jk+wBuaPosFmj4HrJk+NF+ZPnB4mT6vHpo+9UKbPoxznD4WL50+2aadPthcnj75op8+mFahPkbyoj4yLqQ+MjKlPkojpj6VFqc+gDaoPrhHqT5/Dao+ytOqPiUNrD6b7q0+OCawPnUjsj46hbM+lri0PpPptT7/Z7Y+eoy1PqVzsz48IrE+uxewPg3YsD61nbE+qemwPhC3rD50b6M+mUaVPgUlgj6YuVY+nA8mPqiA7j0JPaI9k8haPU4jHz1n0/08iS69PDqfijy2I1M8HeMzPEawNzyF+gs8m9+hO7n3Wzv0ErI7SciAPJWwGz1MMoc9FIS/PUSb9j0rtBo+08k/PleyZD7GWIA+FIOIPiySiz7TNYw+1s+MPoHOjT7lUY8+VQ+RPhTzkj5rZJU+KcqXPhFRmT7++pk+IP6ZPsL1mT68GJo+jS2aPupCmj5LWJo+rnaaPr/dmj7+v5s+ySadPimonj7UtJ8+/3+gPraKoT7+DaM+dtGkPj1Ipj4dRac+ORmoPqfeqD4Og6k+CxiqPltmqj4AQ6o+RgCqPj0Zqj6P5ao+QDisPkuvrT5pAq8+wIKwPphqsj4X37M+CeizPvNrsj4YdrA+816vPquIrz7dQbA+JdawPjI+sD79q60+7U6oPq00nz7+DpI+upyAPnfZWD6L7jE+AxQSPu02+D17jNI9A7aePclvSz0mB988meR6PFaeWzxCnDg8RfLmO/5ioju7C9g7os88PbETwj3rQRU+0fk7PtCyVj7UeXA+3NSDPo8IjD6iL48+2jOOPlLkiz5VhIo+CBOLPkYdjT6/zo8+yFmSPvqjlD6D85Y+lu+YPqskmj7ijpo+CXmaPhtlmj4pkZo+6PiaPqmemz4yY5w+piKdPij9nT5zJJ8+q6ygPpc8oj6eVqM++jukPrRVpT4PsKY+qf6nPs/EqD4KBKk+6z2pPlOXqT7K4qk+fRKqPlTgqT7pJKk+cyOoPmlCpz6i+aY+qHKnPrWhqD7PKKo+dPerPvtcrj5BubA+MgayPqDbsT6+xrA+hfmvPjkDsD6fTbA+OhywPlD9rj6U76w+QkyqPs2Fpz7SQqQ+q6SePvazlT5Hpoo+TJF/PopgbD46qE8+QwkdPl3avj0K9i49TIKCPFI8KzzWzxw8BqTPO2B8mDsqP7E7p2+NPU4aCz47108+GeB+PldCjD4C2JQ+bVCXPp76lD4Q75A+KCuNPsg0iz7pFIs+dVGMPrFnjj7SvZA+p8iSPmKplD42tZY+UKKYPkX6mT5zlZo+7sKaPh36mj7hhJs+UX6cPuLSnT62SJ8+xKCgPrXnoT7HRaM+DMqkPiUwpj5NHac+LtinPjenqD5tcKk+OuepPre3qT4UDKk+ioOoPlRUqD5GTKg+AU2oPrT5pz7MIKc+z+qlPpaSpD5ljqM+1F6jPm5npD70NKY+5DuoPpzLqj4PzK0+D3ywPogesj5MVLI+fu2xPrP2sT4iFbI+JsWxPnBcsD6BQK0+SkipPrtFpj6fJ6Y+IIyoPioqqz4g3as+CcWpPvE0oz6Q648+iGhWPmD1+T1AvEw9RDZZPBlhujswlcY75ROQO2tCSjtDxiY737iIPVrsAj42X0I+SkVwPvgphz5+N5M+tPSXPpLplj5QvJM+40mQPvUJjj7mII0+/oeNPtPsjj5DjZA+tdmRPplFkz6JTpU+t6KXPtmbmT4szZo+Y2ubPojwmz6V1Zw+bVSePlpIoD7+VKI+1hmkPlWbpT5+/aY+rk+oPoljqT4a+6k+c1iqPqKlqj6Ar6o+6DWqPncZqT4EpKc+NnimPifQpT73hKU+VoKlPnljpT774KQ+sAGkPmfYoj7BvKE+VkShPisYoj7b2KM+I76lPhsdqD6Uf6s+MI2vPjossz4O/7Q+qDu1PgtYtT6NaLU+0SO1PkHwsz7vJLE+6WOtPmeuqT6GLqg+H8ypPqzgrD7Cx64+MROtPsC/pD6kA44+CXdNPiMu5j2ZKS09BEULPDin8To0jhM7O4bmOpaZjDq99eA5xy4qPXRAoj0hgfY9gXQfPju4QT4XOmc+jHKCPtK9jD7eXpI+lZ6TPhCJkj6fc5A+BzePPkNgjz4fDZA+xKSQPnPWkT6gK5Q+wC+XPkYDmj4s65s+XPecPn/AnT4D5Z4+bq2gPrn7oj4RTKU+hSqnPqqbqD4wuak+cJ2qPgYvqz7sTqs+vz2rPlwMqz4scao+JzGpPo9ipz5DcqU+H/WjPnYZoz4Rv6I+v+eiPpI6oz67VKM+HBujPpGLoj5i4KE+d4OhPpsUoj77cqM+weqkPgfLpj4PKqo+xzGvPnektD52Rrg+/0m5PqpguT4pa7k+bnW5PvcOuT6pP7c+sdyzPoWHrj7XWKg+C2iiPjr0mz4jB5Q+nuyJPqkJeT551k0+8+wPPvWcnD3vzOc8jU7XO+yMMzvmsFI7U+hwOx4QgDs+BUs70wNDPIyCyzwL2DU9mnuMPbq0zD3rbQ0+zJM0PlMhWz7IAns+xV2IPlSWjj6NipA+LPqQPkU/kT51KZE+iiSRPiUekj4ClpQ+Kh+YPoqnmz6AN54+bbGfPobJoD5mG6I+Y9SjPjLtpT4e4qc+xFupPnBtqj6oFas+ZG6rPuJvqz5XHKs+trSqPqovqj58LKk+b3GnPhVDpT4GMqM+v8OhPu8UoT7n/KA+OYWhPupmoj4JJaM+qI+jPvOqoz7LpqM+faSjPgL1oz5hxKQ+AKOlPgvWpj4V3ak+1mCvPi5Btj44mbs+4ny9Pj2uvT6b770+GVi+PvaCvT6lX7k+1nexPi6kpT4QXJc+Ib2IPmf/cz7T9VU+qKg3Ppk1GT4j2u49RwajPXy1Nz3gLLA8em5JPPpfPjzYmlc8W/ltPLDPdTx7fUc8AAAAAFYznDqmMr07ozRpPCIE+TylamM9EVy0PSjHAj5LiSo+8WxNPq6Eaj7ceYA+uPSJPq0okT587ZQ+kNCVPnzhlT6NWZc+YKmaPgCGnj7RfqE+vTSjPhV4pD7A06U++zqnPsukqD78r6k+qVWqPjXLqj4C9qo+JNyqPih9qj4R8ak+FmupPi7HqD5ll6c+w7KlPq2Foz5RrqE+upigPu9QoD67qKA+wqmhPpgaoz4jY6Q+mkClPm/QpT6dSaY+/5CmPr+Zpj5xwqY+DeumPrWcpz6Ncao+VxqwPsTRtz5dnr4+2ivCPvBewz6B1sI+h7C/Pmr2tz74o6o+XK2ZPi7Uhj7FsGc+pLBEPmrCJD6tvQc+IxvcPSWXrz1ciYg9NPVKPQLMED3neN88N5/LPEqm1DxeUuk8WYX4PCgn9Tx+HsM8AAAAAAAAAAAAAAAAAAAAAMKeJTtK+B88ju/IPNKSST3ezaM9wlnpPc/OFz6MRDs+LCxiPvKKhD4z0JM+hqybPg5mnT66d50+AD2fPgGLoj6DUaU+vdCmPqPppz7bDqk+3vupPvyGqj4Jd6o+jSCqPk/jqT62pKk+OFapPiHtqD5oeag+ThKoPiR5pz7lQ6Y+zHSkPs+Zoj6bQ6E+i7GgPi/UoD4vhqE+BeOiPvm+pD7YaaY+c4SnPro1qD7txKg+iBOpPobbqD5Mgqg++w6oPq2lqD4Es6s+PF+xPoiMuT5ffME+B0LGPg0hxj58Qr8+WXaxPpytnT50doY+/4RfPh1TNz5iBxY+DVH4PRxY0T1dXLQ9FfmdPa8jij3IkW49+7FLPYSULz193CI9y/EhPR/UKT2QFTU9p304PR6GKj3odQA9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2sAAO7wTCTwZKKk8nBYkPQzrhj1Yscs9zkwTPgi+ST6w+n8+J4iUPkdwnz6oYaM+Pv+kPhbfpj7voag+T5mpPlNDqj7f3qo+KTurPhQJqz4JJKo+xBWpPmxWqD6p4Kc+JpqnPidppz5hRac+iCenPgW3pj5qlqU+SAakPu2toj4k/6E+5f2hPhBuoj6rOqM+1ZukPi1/pj4GOqg+SlKpPlrdqT49Kqo+DziqPj68qT6hIak+Tn+oPk+iqT5jqq0+cp2zPkO7uj4tlr8+1P++PhSWtj7xUKU+C2mNPgAoZT6vgTI+WLoJPpfe2j3Yd7k9wKGoPQKhoT2gHJ49VNSXPUWgij2KaXA93A5PPcZoPD3xKzw9XEhGPfA8Uj0ZZ1g9XVJOPYqxLT2Ki+88AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD6qJI6n9WuO/3AcDwUXAg9J5CHPdM46j0OcDE+GYptPk/Ujj79m54+K7amPugFqj5sAas+5SCrPhwcqz457qo+D8aqPho7qj43M6k+qB+oPhhRpz5U36Y+PbamPsW4pj5G0qY+9eqmPjacpj5AnKU+o2WkPseloz51oKM+AR6kPp+vpD4eUKU+iVWmPjfFpz5CGKk+986pPpTqqT4Isqk+Tk2pPnegqD5VI6g+VkeoPhEaqz4JY7A+tnG0PjRYtD6fYa0+FAegPu1yjT5yom0+ivU8PukkDz7579Y9QNipPedHlj2auJQ97duZPfYTnj1OZJw9ryGRPYW4dz1ZRUU9LtIgPQXhGD0XdCo98NxEPZqZVz05hlY9FVA7PRsdCj0eiKE8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF4QMzpv8Jg7kKaQPDQeNj2febM96S0UPqlOUz6NOIY+xxubPsoBpz7Vk6s+qQOsPtQQqz7A/qk+N42pPqImqT4lmqg+1R2oPq62pz5mh6c+dYGnPvmBpz7Keac+1GanPvz5pj54CqY+si6lPqTwpD7WXaU+qBymPoWfpj7P56Y+vVinPioDqD70jqg+sJeoPoUaqD6XZ6c+qsumPkFSpj5+kKY+3ISoPrQlrT583rA+/+asPpF+nj62y4c++IpePgCWMj4xgQ0+oFrfPbbHsj1PPpg9V4iNPSMFjz2bFJc9vBuePSF+nz2ewpg95KWGPVQpUj2YWBI94xXNPFVJxTwqRQI99wErPTkHRT18gj09QIsUPTDtuDwpfyU8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGx7xOgYjCzyluNw8FKqCPeqs8D1CPzk+ghV4PvcdlT6SnqQ+ddmqPgkDqz63T6k+WcuoPn/4qD79Mak+vnupPiG1qT4B3qk+ZtKpPpVxqT6I0qg+Vi6oPuBtpz7he6Y+st6lPu7kpT6jaqY+BRWnPqZZpz58OKc+4wenPoPZpj7lgqY+4M+lPtnQpD5d7KM+DIKjPgbWoz5Xb6U+aLSoPkRbqz7sq6Y+7SOVPhN6cT5ULjM+v1sBPkz1xD30yqU9HLOZPd04lD3H6JA96IyQPdHUlD0EtZw9QzaiPaRzoD1Z1ZQ9uZR3PWndLT25Jcg8P3hUPKnXWjyc3rw8d3gLPfyXIz0rfxM9PE3MPC/wUzybTIU7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQloQ79aiXPO4KRj3a3sI9xXQfPoGBYz6wG48+M8+hPi0uqT5ttKk+5HOpPsAXqj5q9Ko+1MyrPuJxrD7lo6w+Fi6sPpgVqz6Ntak+6nuoPmV6pz7ViqY+vPqlPnHupT6sLqY+DnmmPt1Ypj5RxaU+jAWlPk4spD63M6M+gxyiPlYVoT71cqA+r7agPn+Joj65N6U+pf6lPmBPnz5IBow+yr1bPkXYGj4HztA9JS+bPcgwjD1Q7I49P9uUPeJPlT3yWpI9jAOTPYb/mD2VrKE9G/OlPfIeoT3/p489lIZdPf7WCT2PIX08t8+8O+a6BDzeTo48z7fUPK/m7TzAkMI8bkBvPMgp1ztd/MA6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABnL6M6ukGjO6IGazzXlxA98yiZPU05Cz7AqlQ+nqmKPn2Ynz5kuqg+almrPmQ6rD6AE60+nguuPlC6rj5Gkq4+iWCtPlh5qz5sfKk+P+GnPra/pj6W26U+K0SlPuABpT6g06Q+XJKkPkf8oz5qCaM+a+yhPni7oD4iiZ8+ToqePr8anj5ngZ4+U2SgPseJoz41yKM+UAqbPn4qhT4DoEk+0nQIPst/tT12Yo49JviMPSxCmD3VZp49stybPaFJlD3yvo894lCTPdM1nD2grKQ9/EilPUoymz3PFoM9HMA5PRmyzTznmBo8DhhDO9nkyDs6tU88DJONPPKtjTxsTEg88ejTO+qwIzs1DtU5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADW/Ic6DPwpOy/KhTsDiQg861XEPEynfz3olv89KexLPmVciD6Jq58+dQyrPhWSrj6TMq8+zqivPv7urz7v9q4+6besPncPqj4wyac+lRmmPlT7pD5NNaQ+3LejPu9voz7h9qI+IzOiPo05oT6EHqA+FPmePuHZnT6855w+D4WcPpAynT5iap8+3OmiPp/Soz7ntpo+YwqDPmG5QD7lp/g9nXefPVQ4gT0zTYo9ugudPaqypj0wN6Q9Dw2aPa+ajz09Eo09ZgSTPX7dmz34/p89k66YPS9chj0kz1A9/bcFPZ+dgjwJ6ps7FB/LOthIjDsGXfo7lbYSPESU8TszRX87jhy+Ov6l1TkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKlNk51vyHOln22ToZdwg7qqjQO4K1xDwLBH89Vr77PRJvSj71Fok+Y/+hPl70rT59xLA+MX2wPkqcrz45WK0+WPOpPqW2pj7QeqQ+r/6iPvoLoj4SjaE+dXChPi53oT6RCqE+yxOgPtQFnz4AG54+CkydPlmlnD6qZJw+WQqdPsk+nz6rvqI+UvijPiKYmz5bK4Q+RqhBPqXT9T2CZJk9xoJzPRbBgT2hG5U9+DahPfMroj2WkJo93c6OPcHnhT27VoY9yumMPTHykT1qj409Ut53PQz+Qz33VAc9kT6aPANYAzxx0Og6uHbhOU6iyTqnciA7QokhO/Ip0Dpt4PI5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADFqwTq9xHE7Psn5O2YrjjzrdxM9JX2SPcHVBD6qDVA++duLPrpgpD5So64+HL+vPuVWrT7Kjak+jG2lPrQRoj66JKA+xxOfPo9+nj6Nfp4+/AyfPnysnz6npp8+9++ePptGnj4F6p0+YamdPretnT4qZ54+h3agPqbqoz6hEqU+y72cPk6QhT5FW0Q+/9/5PWvjmj2rI3Q9iY5+PajqjT0RJpg9nr+YPY0Wkj1Meoc9dJV5Pcg9cD3TJXY9L1x/PV3LfD2BHGE9xFQtPVvs5TwlJoM8snIAPPvOOjuLiPQ5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAhN85vR3BOhVEpTvGdx08ycN8PPji0Dz/+BU9vW5VPZjKpz0lNQk+vnhSPqbUjD6Ne6M+5VyrPnWoqT4aqKQ+kTGgPn4XnT6knJs+MyubPt9Gmz4lB5w+M1+dPgaqnj61OZ8+8jKfPmlhnz542Z8+CUugPu4boT4BO6M+5c6mPvuCqD4nv6A+vIKJPvENSz4fKgE+C/2dPYjNcT1jVHk9Cx+IPZ7YjT1GJ449FeqFPTS7cT0wW1o9V+BNPUYkUj1SOFo9UUFZPZgVSD3myR49b1zNPNqNTDz9S5o7deTVOtKI3jkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAErP3jmOQYs6dhunOo5BizpKz945AAAAAAAAAAAAAAAADZDZOdhRwjpGXWA79HLGO44NNTzXR4k8zrG4PBM5Az28kCc9YTE/PeJoXj3OSZ092fsEPu6FUj6JV4w+lYegPoq9pD4wg6A+C8abPvXpmD7j/pc+H1SYPq9lmT59C5s+yh6dPtoLnz7HSaA+CSmhPtFGoj5kjKM+y7ukPuV8pj6A/qk+uv+sPggepz5CBJE+9axYPuTCCj6iA6o9anV8PUzadz2AxYI9IaKAPYwjdT0w8GY95WFLPQk5LD0NsBg9aLsXPVCOJz2Jxi49mZgjPWtcCT3Wpr48Gx1MPGp2izvmzAU6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE/mvzomlIc7Pge3O47cpjstKC47Q0P6OQAAAAAAAAAAHPDCOsDvrjszMCc8u+BlPLmwjjyQAqY83s27PIA/6DyF+Ao9PXwYPaZeFT16iyA9VhKKPbsdBT5EZFY+ZHaMPmzwmz6Q+5w+bgWZPqZPlj5vLpY+VXKXPkuGmT4qApw+Y6mePi0aoT7j9qI+KKKkPqF5pj6yQKg++wyqPqPLrD5sMrA+KbitPhqNmj5tS2w+zZIZPjyauT2S24c9mcZ9PbxBej3WuWg9W49KPUZ6Mj2eKxw9n+X8PIqjxjyt5bA8y7XCPNc56jzWmPI8B4TQPDGAnDxdwz48nDmxOyfywjoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK1bFTtICvM7Edc+PB+DTTz6nBU8a06KO194yDo6UdU5dqU4OwXRJTxwzJg8wATBPNSIvjyD3KU8ugeSPNCjlTztY588WJaoPIzznjw5fYY8Oc/dPPX+iT3jwg0+Gs1ePvHyiz4viJc+ZreXPv2glT6CEJY+ZjKYPtwumz5sYp4+knGhPmklpD7mWqY+GnyoPi6vqj7yi6w+JtKuPpX3sT57fbE+U5ijPjBngT7sbyo+eqHIPcMhiD3UGYA9+GZ2PawLUj23CCc99N0BPZAd0TxRx6A8uMRiPGJAKjxMCjQ8c+9xPEATlzzXApE8gE9RPH3W/zvlaoA7HjnDOtt/2DkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOmXFDuHUhE87laHPLyTqDzaIJM8CrYsPKqJizvEUoU6v9NlO+0sTjyVY7o8Vw3gPJUFwTy2TYE8UBMePHSF7jtJgMo7arHFO+QJ1jtjI7I7DyURPAsA7TxFbKA96kwcPtH9Zj4BWYw+4sqVPqO6lj7PY5c+5PuZPuK1nT5GY6E+vZGkPuY2pz6hZKk+OXirPlCKrT6cOq8+76CxPlpDsj7+8qc+QGqLPgR3Pz5XT9s993WCPUXTXD1stWA9L6VBPabfCT1F1bY8sy9xPKCiITwq7rw7IpJKOy6GTTt6B8M72TcYPK8lLDw+Kgc8jCqHOwWPxDptO905AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALVPuzrmF/U70aCIPAAEvTyDMrU8PHhnPFv2uTvr/J86I/k8O78sMDxJ/KE8Un/APBkgmzyzSyc8xLNjO79WhDr+vdM5NQ//OYFpnzpnS786YplJO5shMDxH6hY9b+e7PZTdKj7Hu3M+h5+QPjPJmD6sQpo+60+cPn8woD4B+qM+vA+nPvhwqT6tOqs+z6qsPgcYrj6i2K8+7zqxPi25qj7oapI+waVTPk8f+j0d4Ic9FFBGPaKcQD2KGCw9z6LsPHibfDwKCu07xn5gO+br2zpqi/M5AAAAAAzApTq8goo7zZrTOyZY0DvIuoA71KqLOgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWT0jn4SIg7rVE/PCkIkzyTQpg8iI9PPIcGqDvEUoU6TcHNOqG82TvKKFQ8e3mAPIjfTzx6Bc87Qpy8OgAAAACaWOU5apfLOkZRITu/CyI7SGw6O/cGlzse92U8w/Y7PQGm3z368kI+DtCEPlL2lz5tLJ0+waWePmXToT4WT6U+sC6oPtE6qj7Hdas+avCrPm7CrD6Xu64+rWKsPlKKmj7C7Wk+368PPs2glz3Kg0E9NHk3PY4BJz1qA+g8kptjPEx6jTst50M6AAAAAAAAAAAAAAAAAAAAAAogijoDl0g7vIKKO3k6gDtv5Qo7unffOQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADfxNk6hoC8OzfTGTwWUCM8JW7hO1h0Kzs6UdU5wt7qOaJ+OTvIncU7MHzuO2srwzu4YDM7rYNXOognxjrG9oQ7kMoFPO97LTwFJRs8MmLeOzrqizustKA7hQOYPAr+ez0figs+N09gPjhJjz73/Jw+cmagPgiZoj5zaqU+wwCoPma3qT4Zeqo+zWeqPquUqz7w2qw+C++iPhBThD5tmS0+J9S3PfwfTD05NjI90lYuPYUoAT0tboY8gQKuO9HTJDoAAAAAAAAAAAAAAAAAAAAAAAAAABAA3TkKIIo6C8ClOgogijoQAN05AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADbGe4548nNOtqBIDur3h87xvbJOubm4zkAAAAAAAAAAIQ8hzp1JEU7mT+WOwjroDv4G3s70W+JO+MG8Ttb/FU8/RihPIdisDxsXY08iPckPAT8cDtR4qQ6FfmrO0uT5TznbK497WYsPi90fT56+pc+4eugPpPQoj46s6Q+kwmnPk6iqD78Yqk+auqpPsbwqz6KX6k+0VaUPts9Vz5n1/g9LTWAPfYbOj15UTU9qPUTPe7qqzzyfQk8bqL8OgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhQfcOQK+/zqkcqY7YdMWPJu1Nzxb1S08SBkyPBfVZDzFpao84RjhPKwQ3jz8maQ8gOwqPAqaLTsAAAAAWP4xOsCXFzweNDg9+8jvPQCLUT5U+Yw+9/GePj7roj4u8aM+MQGmPjzYpz7AU6k+8JyrPi0brT7mGKI+V+WAPiLsJT77NrE9vadWPcLFRD2r0Ss9X5zXPPocNzwZU0g7Kg8LOgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtGPJOgumtzslmEQ8JZ+fPLZetTw0bZ48edKFPNJUhDxN5qo8JRPOPHcvujymxH48wF/yO7AQ4DoAAAAAAAAAACtY1zoHAJ488RqWPeGiIT7qXng+xq2YPpuOoj5cDqQ+BMmlPnsQqD4t1qo+xJGuPpvFqz4lz5Q+cshTPsoi8j2mkoE9jLJKPQzMQj00KA89uHyJPJNglDvqjuU5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFWeA5Ye+COzu1QjzerLU82dQAPdeyBD2Ef9A8T7iQPPGBVDyxP2I89Dt2PEf8RTyNYvA7SYQ/O1INAzoAAAAAAAAAAAAAAAAUueM77OQoPUss6T1421A+002OPkw+oT5uP6U+IGemPtcjqT4xg60+pMWwPv2FpT7bHoI+uwQjPmLEpD1cyz49UZE1PUTdIj0YI8s8GO0dPA3M2joAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADLN4w66K7OOwKOhTxntuI8hHYQPUK0Bz14br88lDtVPNqAxjvIJY47KtqMOwaFSDu4PtQ6sErxOQAAAAAAAAAAAAAAAAAAAADMrw87HzukPCHfmz3Axig+BT6BPixunj44cqc+NAmoPuGbqj5NsK8+2P+uPvXrmD7oxVc+E8DoPXVHSz0QGgI9JjgHPRG61zzf7mU8cIuVO0Iu6TkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADyEdI5msu9Oor3NTsCj2Q7tpM9OwbS0DqcY+Q6oPPKO9htbjyPlr08d9PePDEIwTyzhXY8cSvcO4dRyToAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADW/KE68f0WPMJBQT2YnAE+7ehhPlqKlz7rtag+QUCqPmO0qz5pFa8+r5emPnrjhT4vkSc+mwiWPcqm1zwR2pY8AgGePPQHXTw7iMU7cB3YOgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADZ78jkgOy87rTXeO0rbMTxyWUM8xMMSPNJfkju4RBE7O16MO8p5EjwmQVk82zNrPAaaOjxX/do7oQYmOxUV2zkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACaYsI6wtOjO8Ck2TyzyLc9Ibk6Pp20ij6HlaU+lh+rPuaQqz6jOqo+l4aXPoYXXT5JJfA9riIoPZ45LTxLe/I7sSHwO18XkTv+Kcs6snfZOQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVgNY5vufGOvQuhzt62B08w6SLPMeAtzyr+q88FIBuPPZx0jtJeOw6XgrHOiBEPDti54I7YWGCOyzFOjsL88M6fZPXOQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADW/KE6DHxKO05QTjxfEWY9mxgPPghAcD7OCpw+tvCoPqRSqT4/hqA+1HGDPhj7Kj5gPZo9g3aWPPyMFjsr5rI6JBWVOjqI7jkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANEIY6YTmLOx8EKjzyV5w8UH7hPINV/TzSTNc8ra+FPJGJ1TukUZY6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASlwE61vyhOmVzaTt1Yek8q8TGPSeKRD7OJ40+N6ijPpYEpT6HKJM+GFZbPghw+T2sKjE9re7FOwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADIgiw6tSEXOwKqbTulwW07nmgXO+A/LToAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQ4KA6J3O6OwsMZTzD7788FDP0PGiB7zzt6bA8kvNCPA5jhjuggvA5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACPl0E8VTaBPffsGz6RWnk+NEKcPvctnz6QfIQ+/08yPkLurD0aTLU86wmoOgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI9jZOV6cvzqnAxc7d0MXOz0bwTqqFTA78moIPOL7ajyfAII8UMM9PHjInzuFp2c6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANEIY6dAqpO1AwTjzcrKA8yMO3PAhenTytzkQ8Rai4O8A0zToAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABI2Yo7jXAjPXc99j2ZFlw+6f2TPjjblz5Vl2w+ne0OPmghZj3Aox88AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkC3aOlMaxTsnQCY8Z480PEa4ADwXKOk7wed0PGYR0Dzkfe082FKzPJyJJDyzyBA7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVgNY5j/4tO26d4TvTfik8Yu4xPJbGBDwzuIU7ZfXMOtbQ4jkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABe/0E6USTFPAgAvz1cykA+5aSIPtgsjD5k900+ajTcPaFRDz0CNF07AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvkhdOxpETjxGDro8/O7dPF3RtDxtpYU8dNGkPCay7DwtDAQ9lxbHPL2IOTykvS07AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmojuOZJPzTr4ux87++EeO6MzyDrI6OA5AAAAAAAAAAAAAAAAAAAAAIo91zl2hoY6KG6hOnaGhjqKPdc5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhd1dPCFYhz1K1Bg+n5NfPq1bZD4aiCA+0F6XPUY5nDyruhE6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH+KNO2jMjTyrcQw9QIk7PXU1Lz1Azf48L13FPO9HwTx/M8Q8GLuUPKDhDjyzyBA7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHaGhjoUKCg7sslJOxQoKDt2hoY6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAix/OO8XIHj0fWcY9pscTPuPYFT6g5Ms9DsAqPa2kCzwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5vFwO29Cijwuzxw9/PlpPVx1cT3ukDM9v1jPPKwmWzxBxxw844/iOwNJUzuFp2c6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL91johXoY7wj2hOyFehjsC/dY6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0D7YOg0EhTyrLz09c2OPPRPFjz0bWDw92fqFPM+CDTsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOqoFO1NERDw9YgM9K4hXPUt+bT3l9jQ9dPm2PDIFzzsiMJE6A03oOQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMw1Bjs/w6c7slDJOz/DpzvMNQY7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK17WzssKzs8usuQPHaTjzyc2TM8gvdHOwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYj4UOm7hxTvLaKM8pyMRPazuJj0fhAE9bdx5PCFzYDsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';

  var _map = null;
  function alphaMap() {
    if (_map) return _map;
    var bin = atob(B64), buf = new ArrayBuffer(bin.length), u8 = new Uint8Array(buf);
    for (var i = 0; i < bin.length; i++) u8[i] = bin.charCodeAt(i);
    _map = new Float32Array(buf);
    return _map;
  }

  /** Hình học suy ra cho một khung bất kỳ. Chỉ là ƯỚC LƯỢNG khi khác 1080x1920 — xem chú thích đầu file. */
  function geometryFor(w, h) {
    var shortSide = Math.min(w, h);
    var s = shortSide / REF_SHORT;                 // hệ số co giãn theo cạnh ngắn
    var inset = Math.round(shortSide * CENTER_INSET);
    var star = Math.round(shortSide * STAR_RATIO);      // cạnh ngôi sao trên khung này
    return {
      cx: w - inset, cy: h - inset, scale: s, starSize: star,
      box: { x: Math.round(w - inset - star / 2), y: Math.round(h - inset - star / 2), width: star, height: star },
    };
  }

  /**
   * TRỪ NGƯỢC CHÍNH XÁC: original = (watermarked − α·L) / (1 − α).
   * Không vá, không làm mờ, không lấy pixel lân cận — mỗi pixel được giải đúng từ phương trình
   * pha trộn mà Veo đã dùng để đặt watermark lên.
   *
   * @param {CanvasRenderingContext2D} ctx
   * @param {{cx:number,cy:number,scale:number}} at  tâm + tỉ lệ (từ probe hoặc geometryFor)
   */
  function unblendContext(ctx, w, h, at) {
    var g = at || geometryFor(w, h);
    var map = alphaMap(), s = g.scale || 1;
    var bw = Math.round(MAP_W * s), bh = Math.round(MAP_H * s);
    var bx = Math.round(g.cx + OFF_X * s), by = Math.round(g.cy + OFF_Y * s);
    // Cắt theo biên khung — watermark sát mép nên phải kẹp, không thì getImageData ném lỗi.
    var sx = Math.max(0, bx), sy = Math.max(0, by);
    var ex = Math.min(w, bx + bw), ey = Math.min(h, by + bh);
    if (ex <= sx || ey <= sy) return false;

    var img = ctx.getImageData(sx, sy, ex - sx, ey - sy);
    var d = img.data, iw = ex - sx;
    for (var y = sy; y < ey; y++) {
      for (var x = sx; x < ex; x++) {
        // toạ độ trong map (nội suy gần nhất — map đã mượt nên đủ)
        var mx = Math.round((x - bx) / s), my = Math.round((y - by) / s);
        if (mx < 0 || mx >= MAP_W || my < 0 || my >= MAP_H) continue;
        var a = map[my * MAP_W + mx];
        if (a < 0.02) continue;
        if (a > 0.95) a = 0.95;                    // chặn chia cho ~0
        var o = ((y - sy) * iw + (x - sx)) * 4;
        for (var c = 0; c < 3; c++) {
          var v = (d[o + c] - a * LOGO) / (1 - a);
          d[o + c] = v < 0 ? 0 : (v > 255 ? 255 : v);
        }
      }
    }
    ctx.putImageData(img, sx, sy);
    return true;
  }


  /**
   * Lấy alpha-map. ƯU TIÊN bản hiệu chỉnh sẵn có trong extension ('96-20260520' của
   * GargantuaX/gemini-watermark-remover) vì nó được đo trên NỀN ĐẶC → sạch, đối xứng, không dính
   * nhiễu. Bản tự đo (nhúng dưới) chỉ dùng khi file alpha-data không được nạp (vd content script
   * ChatGPT/Grok). Đo đối chứng trên video Veo thật: bản GargantuaX cho sai lệch 9.88 so với 13.60
   * của bản tự đo — nên thứ tự ưu tiên này là có căn cứ, không phải cảm tính.
   */
  function preferredMap() {
    try {
      var A = root.WatermarkAlphaData;
      if (A && typeof A.getEmbeddedAlphaMap === 'function') {
        var m = A.getEmbeddedAlphaMap('96-20260520');
        if (m && m.length === 96 * 96) return { map: m, size: 96, src: 'calibrated-96' };
      }
    } catch (_) { globalThis.SEOSONA_swallow?.('VeoWatermarkProfile#preferredMap', _); }
    return { map: alphaMap(), size: null, src: 'measured' };
  }

  /**
   * TRỪ NGƯỢC CÓ HIỆU CHỈNH THEO TỪNG KHUNG.
   *
   * Vì sao cần: α cố định thì mỗi khung còn lại một mức dư khác nhau (nền dưới sao đổi liên tục,
   * mức nén mỗi khung cũng khác) ⇒ mảng watermark NHẤP NHÁY qua các khung — người xem thấy là
   * "giật". Bản cố định trước đây mắc đúng lỗi này.
   *
   * Cách làm: mỗi khung tự dò hệ số gain khớp nhất — đo dư lượng so với nền xung quanh rồi chọn
   * gain nhỏ nhất hoá dư lượng đó. Kết quả từng khung đều bám nền của CHÍNH nó ⇒ hết nhấp nháy.
   * Đây là ý tưởng "adaptive per-frame feedback" của allenk/VeoWatermarkRemover.
   */
  function unblendAdaptive(ctx, w, h, at, opts) {
    var o = opts || {};
    var g = at || geometryFor(w, h);
    var pm = preferredMap();
    var map = pm.map, MW = pm.size || MAP_W, MH = pm.size || MAP_H;
    // Cỡ vẽ = cỡ ngôi sao THẬT trên khung; tỉ lệ suy ra từ map đang dùng (map nào cũng khớp).
    var star = g.starSize || Math.round(Math.min(w, h) * STAR_RATIO);
    var bw = star, bh = Math.round(star * MH / MW);
    var s = bw / MW;
    var bx = Math.round(g.cx - bw / 2), by = Math.round(g.cy - bh / 2);

    // Đọc rộng hơn hộp để có VÀNH NỀN sạch làm mốc so sánh.
    var PAD = Math.max(6, Math.round(Math.max(bw, bh) * 0.18));
    var sx = Math.max(0, bx - PAD), sy = Math.max(0, by - PAD);
    var ex = Math.min(w, bx + bw + PAD), ey = Math.min(h, by + bh + PAD);
    if (ex - sx < 8 || ey - sy < 8) return false;

    var img = ctx.getImageData(sx, sy, ex - sx, ey - sy);
    var d = img.data, iw = ex - sx, ih = ey - sy;

    // Mốc nền: trung bình vành ngoài hộp (mỗi kênh riêng).
    var rs = [0, 0, 0], rn = 0;
    for (var y = 0; y < ih; y++) {
      for (var x = 0; x < iw; x++) {
        var gx = sx + x, gy = sy + y;
        if (gx >= bx && gx < bx + bw && gy >= by && gy < by + bh) continue;
        var oo = (y * iw + x) * 4;
        rs[0] += d[oo]; rs[1] += d[oo + 1]; rs[2] += d[oo + 2]; rn++;
      }
    }
    if (!rn) return false;
    var refC = [rs[0] / rn, rs[1] / rn, rs[2] / rn];

    // Dò gain của KHUNG NÀY bằng tìm-kiếm-tam-phân trên dải liên tục.
    // Dùng liên tục thay vì danh sách rời rạc vì gain tối ưu thật sự trải rộng: đo trên video Veo
    // thật cho min 0.60 – max 1.37. Danh sách rời rạc ép về vài mốc ⇒ mỗi khung lệch một kiểu ⇒
    // chính nó gây nhấp nháy.
    var errAt = function (gain) {
      var err = 0, cnt = 0;
      for (var yy = 0; yy < bh; yy += 2) {
        for (var xx = 0; xx < bw; xx += 2) {
          var mx = Math.round(xx / s), my = Math.round(yy / s);
          if (mx < 0 || mx >= MW || my < 0 || my >= MH) continue;
          var a = map[my * MW + mx] * gain;
          if (a < 0.05) continue;
          if (a > 0.95) a = 0.95;
          var px = bx + xx - sx, py = by + yy - sy;
          if (px < 0 || px >= iw || py < 0 || py >= ih) continue;
          var q = (py * iw + px) * 4;
          for (var c = 0; c < 3; c++) err += Math.abs((d[q + c] - a * LOGO) / (1 - a) - refC[c]);
          cnt += 3;
        }
      }
      return cnt ? err / cnt : Infinity;
    };
    var lo = o.gainMin || 0.55, hi = o.gainMax || 1.55;
    for (var it = 0; it < 16; it++) {
      var m1 = lo + (hi - lo) / 3, m2 = hi - (hi - lo) / 3;
      if (errAt(m1) < errAt(m2)) hi = m2; else lo = m1;
    }
    var bestG = (lo + hi) / 2, bestErr = errAt(bestG);
    // CỐ Ý KHÔNG làm mượt gain theo thời gian: đã đo, làm mượt khiến giật TĂNG
    // (1.148 → 1.636 với bán kính 1) vì mức nén mỗi khung khác nhau thật, san phẳng là tái tạo sai.

    // Áp gain tốt nhất của KHUNG NÀY.
    for (var y2 = 0; y2 < bh; y2++) {
      for (var x2 = 0; x2 < bw; x2++) {
        var mx2 = Math.round(x2 / s), my2 = Math.round(y2 / s);
        if (mx2 < 0 || mx2 >= MW || my2 < 0 || my2 >= MH) continue;
        var a2 = map[my2 * MW + mx2] * bestG;
        if (a2 < 0.02) continue;
        if (a2 > 0.95) a2 = 0.95;
        var px2 = bx + x2 - sx, py2 = by + y2 - sy;
        if (px2 < 0 || px2 >= iw || py2 < 0 || py2 >= ih) continue;
        var q2 = (py2 * iw + px2) * 4;
        for (var c2 = 0; c2 < 3; c2++) {
          var v2 = (d[q2 + c2] - a2 * LOGO) / (1 - a2);
          d[q2 + c2] = v2 < 0 ? 0 : (v2 > 255 ? 255 : v2);
        }
      }
    }
    ctx.putImageData(img, sx, sy);
    return { ok: true, gain: bestG, err: bestErr, map: pm.src };
  }

  root.VeoWatermarkProfile = {
    unblendContext: unblendContext, unblendAdaptive: unblendAdaptive,
    geometryFor: geometryFor, alphaMap: alphaMap, preferredMap: preferredMap,
    MAP_W: MAP_W, MAP_H: MAP_H, OFF_X: OFF_X, OFF_Y: OFF_Y, PEAK: PEAK, LOGO: LOGO,
  };
})(typeof self !== 'undefined' ? self : this);
