#!/usr/bin/env node
// P1.T8 — Publish Phase 1 evidence index. Recompute every artifact and accept
// only on hash reconciliation.
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { repoRoot, sha256, stableJson } from './lib/repo.mjs';
import { buildInventory } from './lib/repo.mjs';
import { buildArchitectureGraph } from './lib/graph.mjs';
import { buildMessageContracts } from './lib/messages.mjs';
import { buildStorageInventory } from './lib/storage.mjs';
import { buildHistoryReport } from './lib/history.mjs';

const INDEX_REL = 'seosona-flow/artifacts/audit/phase-01/index.json';
const MD_REL = 'docs/audits/phase-01-baseline.md';

// Each artifact: rebuilt in-memory and compared byte-for-byte with the file.
const ARTIFACTS = [
  { id: 'repository-inventory', rel: 'seosona-flow/artifacts/audit/phase-01/repository-inventory.json', generator: 'node scripts/audit/inventory.mjs', build: (r) => buildInventory(r) },
  { id: 'architecture-graph', rel: 'seosona-flow/artifacts/audit/phase-01/architecture-graph.json', generator: 'node scripts/audit/architecture-graph.mjs', build: (r) => buildArchitectureGraph(r) },
  { id: 'message-contracts', rel: 'seosona-flow/artifacts/audit/phase-01/message-contracts.json', generator: 'node scripts/audit/message-contracts.mjs', build: (r) => buildMessageContracts(r) },
  { id: 'storage-inventory', rel: 'seosona-flow/artifacts/audit/phase-01/storage-inventory.json', generator: 'node scripts/audit/storage-inventory.mjs', build: (r) => buildStorageInventory(r) },
  { id: 'history-report', rel: 'seosona-flow/artifacts/audit/phase-01/history-report.json', generator: 'node scripts/audit/history-report.mjs', build: (r) => buildHistoryReport(r) },
];

function currentCommit(root) {
  return execFileSync('git', ['-C', root, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
}

export function buildEvidenceIndex(root = repoRoot()) {
  const entries = ARTIFACTS.map((a) => {
    const path = join(root, a.rel);
    const present = existsSync(path);
    const onDisk = present ? readFileSync(path, 'utf8') : null;
    const rebuilt = stableJson(a.build(root));
    const reconciled = present && onDisk === rebuilt;
    return {
      id: a.id,
      artifact: a.rel,
      generator: a.generator,
      sha256: reconciled ? sha256(onDisk) : null,
      reconciled,
    };
  });
  // Issue registry is generated from a data source, not a repo scan.
  const issuesPath = join(root, 'seosona-flow/artifacts/audit/issues.json');
  const issuesPresent = existsSync(issuesPath);
  entries.push({
    id: 'issues',
    artifact: 'seosona-flow/artifacts/audit/issues.json',
    generator: 'node scripts/audit/issue-registry.mjs',
    sha256: issuesPresent ? sha256(readFileSync(issuesPath, 'utf8')) : null,
    reconciled: issuesPresent,
  });

  const allReconciled = entries.every((e) => e.reconciled);
  return {
    schema: 'seosona.audit.evidence-index.v1',
    phase: 1,
    baselineCommit: currentCommit(root),
    artifacts: entries,
    verdict: allReconciled ? 'ACCEPTED' : 'WITHHELD',
  };
}

function renderMd(index) {
  const lines = [];
  lines.push('# SEOSONA Flow Phase 1 Baseline');
  lines.push('');
  lines.push('> Generated by `scripts/audit/evidence-index.mjs`. Regenerate/verify with `--check`.');
  lines.push('');
  lines.push(`- Baseline commit: \`${index.baselineCommit}\``);
  lines.push(`- Verifier verdict: **${index.verdict}**`);
  lines.push('');
  lines.push('## Phase 1 Evidence Artifacts');
  lines.push('');
  lines.push('| Artifact | Generator | Reconciled | sha256 |');
  lines.push('|---|---|:--:|---|');
  for (const e of index.artifacts) {
    const short = e.sha256 ? e.sha256.slice(0, 16) + '…' : '—';
    lines.push(`| \`${e.artifact}\` | \`${e.generator}\` | ${e.reconciled ? '✅' : '❌'} | \`${short}\` |`);
  }
  lines.push('');
  lines.push('## Verification');
  lines.push('');
  lines.push('```');
  lines.push('node scripts/audit/inventory.mjs --check');
  lines.push('node scripts/audit/architecture-graph.mjs --check');
  lines.push('node scripts/audit/message-contracts.mjs --check');
  lines.push('node scripts/audit/storage-inventory.mjs --check');
  lines.push('node scripts/audit/history-report.mjs --check');
  lines.push('node scripts/audit/issue-registry.mjs --check');
  lines.push('node scripts/audit/evidence-index.mjs --check');
  lines.push('node --test tests/audit/');
  lines.push('```');
  lines.push('');
  return lines.join('\n');
}

function main() {
  const check = process.argv.includes('--check');
  const root = repoRoot();
  const index = buildEvidenceIndex(root);
  const json = stableJson(index);
  const md = renderMd(index);
  const indexPath = join(root, INDEX_REL);
  const mdPath = join(root, MD_REL);

  if (check) {
    if (index.verdict !== 'ACCEPTED') {
      console.error('[evidence] WITHHELD: not all artifacts reconcile.');
      for (const e of index.artifacts.filter((x) => !x.reconciled)) console.error(`  - ${e.artifact}`);
      process.exit(1);
    }
    const ok = existsSync(indexPath) && readFileSync(indexPath, 'utf8') === json &&
      existsSync(mdPath) && readFileSync(mdPath, 'utf8') === md;
    if (!ok) {
      console.error('[evidence] DRIFT: index or baseline doc is stale.');
      process.exit(1);
    }
    console.log(`[evidence] OK verdict=${index.verdict} artifacts=${index.artifacts.length} all reconciled`);
    return;
  }

  mkdirSync(dirname(indexPath), { recursive: true });
  mkdirSync(dirname(mdPath), { recursive: true });
  writeFileSync(indexPath, json);
  writeFileSync(mdPath, md);
  console.log(`[evidence] wrote ${INDEX_REL} and ${MD_REL}`);
  console.log(`  verdict=${index.verdict} artifacts=${index.artifacts.length}`);
}

main();
